services:
  django-qr-code:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION
    volumes:
      - ./:/usr/src/app
    environment:
      - APP_PORT=8910
    expose:
      - "8910"
    ports:
      - "8910:8910"
